services:
  - type: web
    name: fkits
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_TOKEN
        sync: false # Укажешь вручную в панели Render для безопасности
      - key: CARD_NUMBER  
        value: "6262 4700 5534 4787"
      - key: PORT
        value: "10000"
      - key: ADMIN_IDS
        value: "5009858379,587180281,1225271746"